import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const base = process.env.GAME_URL || 'http://127.0.0.1:8000/heart_at_crossroads.html';
const normal = await browser.newPage();
await normal.goto(base, { waitUntil: 'domcontentloaded' });
const normalState = await normal.evaluate(() => ({ mode: window.heartDevMode, control: !!document.getElementById('stage0k-dev-replay-control') }));
if (normalState.mode || normalState.control) throw new Error(`unexpected developer UI: ${JSON.stringify(normalState)}`);
const specialUrl = new URL(base);
specialUrl.searchParams.set('dev', '1');
const special = await browser.newPage();
await special.goto(specialUrl.href, { waitUntil: 'domcontentloaded' });
const specialState = await special.evaluate(() => ({ mode: window.heartDevMode, control: !!document.getElementById('stage0k-dev-replay-control') }));
if (!specialState.mode || !specialState.control) throw new Error(`developer mode did not expose control: ${JSON.stringify(specialState)}`);
console.log(JSON.stringify({ status: 'PASS', normalState, specialState }, null, 2));
await browser.close();
