import { chromium } from 'playwright';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1280,height:720}});
page.on('dialog',d=>d.dismiss().catch(()=>{}));
const assert=(c,m,d='')=>{if(!c)throw new Error(`${m}${d?`: ${d}`:''}`)};
const url=process.env.GAME_URL||'http://127.0.0.1:8000/heart_at_crossroads.html';
await page.goto(url,{waitUntil:'domcontentloaded'});
await page.waitForFunction(()=>typeof stage2dRouteStrength==='function'&&typeof stage2dLegacyEndingEligible==='function'&&typeof stage2dReadDiamondBank==='function'&&stage2dEconomy?.initialDiamonds===70&&stage2dEconomy?.completionReward===100);
const agency=await page.evaluate(async()=>{
 const generation=beginRuntimeSession('2d-agency');resetGameState(false);currentChapter=10;currentScene=5;scriptData=await(await fetch('assets/data/chapter10.json')).json();const scene=scriptData.scenes.find(x=>x.id===5),box=document.querySelector('.dialogue-box');clearDialogueHandlers(box);box.querySelectorAll('.choice-btn').forEach(n=>n.remove());stats.crown=stats.heart=stats.leaf=0;stats.relationships.dima=stats.relationships.mark=stats.relationships.sergey=stats.relationships.vika=0;const finals=await stage0iEnsureFinals(generation),legacyMark=stage2dLegacyEndingEligible('silence_with_mark',finals);await handleChoices(scene,box,null,generation);const buttons=[...box.querySelectorAll('.choice-btn')].map(b=>({id:b.dataset.choiceId,disabled:b.disabled,text:b.textContent})),markStrength=stage2dRouteStrength('silence_with_mark',stats),newStartStrength=stage2dRouteStrength('new_start',stats);const originalShowEnding=showEnding;let captured=null;showEnding=(ending,gen)=>{if(!isRunCurrent(gen))return false;captured=ending.id;return true};const directMark=await loadFinals('silence_with_mark',generation);showEnding=originalShowEnding;invalidateRuntimeSession('2d-agency-done');return{buttons,legacyMark,markStrength,newStartStrength,directMark,captured};
});
assert(agency.buttons.length===6,'Final scene does not expose all six choices',JSON.stringify(agency));assert(agency.buttons.every(b=>!b.disabled),'A final choice is still disabled',JSON.stringify(agency));assert(agency.buttons.every(b=>!b.text.includes('🔒')),'A final route still renders a lock',JSON.stringify(agency));assert(agency.legacyMark===false,'Legacy Mark analytics changed unexpectedly',JSON.stringify(agency));assert(agency.markStrength.level==='impulsive','Zero-stat Mark route is not impulsive',JSON.stringify(agency));assert(agency.newStartStrength.level==='intentional','New Start route strength is wrong',JSON.stringify(agency));assert(agency.directMark===true&&agency.captured==='silence_with_mark','Known ending is still gated',JSON.stringify(agency));
const economy=await page.evaluate(async()=>{const originalShowScene=showScene;try{localStorage.removeItem(storageKey(RUN_STORAGE_KEY));stage2dWriteDiamondBank(70);const generation=beginRuntimeSession('2d-spend');resetGameState(false);stats.diamonds=70;currentChapter=1;currentScene=3;scriptData=await(await fetch('assets/data/chapter1.json')).json();const paid=scriptData.scenes.find(x=>x.id===3).choices.find(c=>Number(c.cost)===5);showScene=async(_id,gen)=>isRunCurrent(gen);const ok=await applyChoice(paid,{generation});const afterSpend={ok,diamonds:stats.diamonds,bank:stage2dReadDiamondBank()};const stale=JSON.parse(localStorage.getItem(storageKey(RUN_STORAGE_KEY)));stale.stats.diamonds=70;localStorage.setItem(storageKey(RUN_STORAGE_KEY),JSON.stringify(stale));stage2dWriteDiamondBank(65);invalidateRuntimeSession('2d-spend-reload');resetGameState(false);const next=beginRuntimeSession('2d-spend-continue'),loaded=await loadSession(next),afterContinue={loaded,diamonds:stats.diamonds,bank:stage2dReadDiamondBank()};invalidateRuntimeSession('2d-spend-done');return{config:stage2dEconomy,afterSpend,afterContinue}}finally{showScene=originalShowScene}});
assert(economy.config.initialDiamonds===70&&economy.config.completionReward===100,'Economy constants drifted',JSON.stringify(economy));assert(economy.afterSpend.ok&&economy.afterSpend.diamonds===65&&economy.afterSpend.bank===65,'Paid story choice did not persist spend',JSON.stringify(economy));assert(economy.afterContinue.loaded&&economy.afterContinue.diamonds===65&&economy.afterContinue.bank===65,'Continue resurrected stale diamonds',JSON.stringify(economy));
console.log(JSON.stringify({status:'PASS',agency,economy},null,2));await browser.close();
